# -*- coding: utf-8 -*-
"""Educational_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12G3b7_xagzzZzeceHWvkD_h-kJGgSUfc

# 🎓 AI-ассистент для генерации тестовых вопросов

**Возможности:**
- 🇷🇺 Качественный перевод на русский язык
- 📝 Детальное описание изображений (BLIP-large)
- ❓ 5 уникальных тестовых вопросов
- 🎯 2 вопроса по содержанию изображения
- 🎲 Случайные неправильные ответы (не повторяются)

# Проект выполнили:
- Перевозчикова Валерия Дмитриевна (ст.б.: 1032259214)
- Рождественский Евгений (ст.б.: )

## 1️⃣ Установка зависимостей
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers gradio accelerate Pillow torch torchvision sentencepiece sacremoses

"""## 2️⃣ Импорт библиотек"""

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import gradio as gr
import random
import time
from typing import List, Dict, Tuple
import warnings
warnings.filterwarnings('ignore')

print("✅ Библиотеки импортированы")
print(f"🎮 GPU доступен: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"📊 GPU: {torch.cuda.get_device_name(0)}")

"""## 3️⃣ Загрузка моделей"""

blip_model = None
blip_processor = None
translation_model = None
translation_tokenizer = None
device = None

def initialize_models():
    global blip_model, blip_processor, translation_model, translation_tokenizer, device

    print("🚀 Загрузка моделей...\n")

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"📱 Используется устройство: {device.upper()}")

    # BLIP-large для детальных описаний
    print("\n📸 Загрузка BLIP-large...")
    blip_processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
    blip_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large")
    blip_model.to(device)
    blip_model.eval()
    print("   ✅ BLIP-large загружен")

    # NLLB для перевода
    print("\n🌍 Загрузка NLLB-200...")
    translation_tokenizer = AutoTokenizer.from_pretrained(
        "facebook/nllb-200-distilled-600M",
        src_lang="eng_Latn",
        tgt_lang="rus_Cyrl"
    )
    translation_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")
    translation_model.to(device)
    translation_model.eval()
    print("   ✅ NLLB-200 загружен\n")

    print("✅ Все модели готовы к работе!")
    return device

device = initialize_models()

"""## 4️⃣ Функции перевода и анализа"""

def translate_to_russian(text: str) -> str:
    """Качественный перевод на русский с сохранением регистра"""
    try:
        inputs = translation_tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            translated = translation_model.generate(
                **inputs,
                forced_bos_token_id=translation_tokenizer.convert_tokens_to_ids("rus_Cyrl"),
                max_length=512
            )

        translated_text = translation_tokenizer.decode(translated[0], skip_special_tokens=True)

        # Приводим первую букву к строчной для использования в середине предложения
        if translated_text and translated_text[0].isupper():
            translated_text = translated_text[0].lower() + translated_text[1:]

        return translated_text

    except Exception as e:
        print(f"      ⚠️ Ошибка перевода: {e}")
        return text

def analyze_image_detailed(image: Image.Image) -> Tuple[str, str]:
    """Детальный анализ изображения"""
    try:
        print("   📊 Анализ изображения...")
        start_time = time.time()

        inputs = blip_processor(images=image, return_tensors="pt").to(device)

        print("      🤖 Генерация детального описания...")
        with torch.no_grad():
            generated_ids = blip_model.generate(
                **inputs,
                max_length=75,
                num_beams=5,
                length_penalty=1.0,
                early_stopping=True
            )

        description_en = blip_processor.decode(generated_ids[0], skip_special_tokens=True)
        print(f"      ✅ Описание (EN): {description_en}")

        print("      🔄 Перевод на русский...")
        description_ru = translate_to_russian(description_en)
        # Для описания оставляем заглавную букву
        description_ru = description_ru[0].upper() + description_ru[1:] if description_ru else description_ru
        print(f"      ✅ Описание (RU): {description_ru}")

        elapsed = time.time() - start_time
        print(f"   ⏱️  Время анализа: {elapsed:.2f} сек")

        return description_en, description_ru

    except Exception as e:
        print(f"   ❌ Ошибка: {e}")
        return "Error", "Ошибка анализа изображения"

print("✅ Функции анализа загружены")

"""## 5️⃣ Генерация уникальных неправильных ответов"""

def generate_unique_wrong_answers(correct_answer: str, description: str, question_type: str) -> List[str]:
    """Генерация УНИКАЛЬНЫХ неправильных ответов на основе описания изображения"""

    desc_lower = description.lower()
    words = description.split()

    # Базовые пулы для разных типов контента
    wrong_pools = {
        'content': [
            # Научные/технические
            "detailed molecular structure diagram with chemical bonds",
            "complex scientific schematic showing cellular processes",
            "technical blueprint with engineering specifications",
            "anatomical illustration of biological systems",
            "mathematical graph showing algebraic functions",
            # Географические
            "topographical map with elevation contours",
            "satellite imagery showing terrain features",
            "geological survey map with mineral deposits",
            "navigational chart with maritime routes",
            # Исторические/архивные
            "historical photograph from archival collection",
            "vintage document with handwritten notes",
            "archaeological artifact photograph",
            "museum exhibit documentation image",
            # Художественные
            "abstract artistic composition with colors",
            "classical painting reproduction",
            "modern graphic design illustration",
            "architectural rendering visualization"
        ],
        'category': [
            "three-dimensional computer-generated model",
            "hand-drawn sketch or illustration",
            "photographic still life composition",
            "animated video frame capture",
            "infographic with icon elements",
            "technical cross-section diagram",
            "flowchart with process steps",
            "mind map with hierarchical structure",
            "timeline showing chronological events",
            "scatter plot with data points"
        ],
        'purpose': [
            "educational demonstration for student training",
            "scientific research documentation",
            "industrial quality control assessment",
            "marketing and promotional presentation",
            "safety instruction and warning display",
            "entertainment and recreational viewing",
            "archival preservation and documentation",
            "diagnostic analysis and evaluation",
            "comparison and benchmarking study",
            "trend analysis and pattern recognition"
        ],
        'context': [
            "medical diagnostics and healthcare",
            "engineering design and manufacturing",
            "financial analysis and investment",
            "environmental monitoring and ecology",
            "agricultural planning and farming",
            "urban planning and architecture",
            "transportation and logistics",
            "telecommunications and networking",
            "energy production and distribution",
            "retail and consumer services"
        ]
    }

    # Получаем пул для данного типа вопроса
    pool = wrong_pools.get(question_type, wrong_pools['content'])

    # Фильтруем ответы, которые НЕ содержат ключевые слова из описания
    # Это делает неправильные ответы более правдоподобными, но точно неправильными
    key_words = set(word.lower() for word in words if len(word) > 4)

    filtered_pool = []
    for answer in pool:
        answer_words = set(word.lower() for word in answer.split() if len(word) > 4)
        # Исключаем ответы с большим пересечением слов
        if len(key_words & answer_words) < 2:
            filtered_pool.append(answer)

    # Если после фильтрации осталось мало вариантов, используем весь пул
    if len(filtered_pool) < 3:
        filtered_pool = pool

    # Случайно выбираем 3 неправильных ответа
    selected = random.sample(filtered_pool, min(3, len(filtered_pool)))

    return selected

print("✅ Функции генерации неправильных ответов загружены")

"""## 6️⃣ Умная генерация вопросов"""

def extract_key_concepts(description: str) -> Dict[str, str]:
    """Извлекает ключевые концепты из описания"""
    desc_lower = description.lower()
    words = description.split()

    concepts = {
        'main_object': description,
        'detail': ' '.join(words[-4:]) if len(words) > 4 else description,
        'category': determine_category(desc_lower),
        'purpose': determine_purpose(desc_lower),
        'context': determine_context(desc_lower)
    }

    return concepts

def determine_category(description: str) -> str:
    """Определяет категорию изображения"""
    if any(word in description for word in ['chart', 'graph', 'diagram']):
        if 'pie' in description:
            return "circular pie chart visualization"
        elif 'bar' in description:
            return "bar chart or column graph"
        elif 'line' in description:
            return "line graph or trend chart"
        else:
            return "data visualization chart"
    elif any(word in description for word in ['map', 'weather', 'geographic']):
        return "geographical or meteorological map"
    elif any(word in description for word in ['photo', 'picture', 'image']):
        return "photographic image or picture"
    else:
        return "informational graphic or diagram"

def determine_purpose(description: str) -> str:
    """Определяет назначение"""
    if any(word in description for word in ['weather', 'forecast', 'climate']):
        return "weather forecasting and meteorological analysis"
    elif any(word in description for word in ['sales', 'revenue', 'business', 'financial']):
        return "business analysis and performance tracking"
    elif any(word in description for word in ['data', 'statistics', 'chart']):
        return "data visualization and statistical presentation"
    elif any(word in description for word in ['scientific', 'research', 'study']):
        return "scientific research and academic study"
    else:
        return "information presentation and communication"

def determine_context(description: str) -> str:
    """Определяет контекст применения"""
    if any(word in description for word in ['weather', 'meteorological']):
        return "meteorology and atmospheric sciences"
    elif any(word in description for word in ['business', 'sales', 'financial']):
        return "business intelligence and corporate analytics"
    elif any(word in description for word in ['medical', 'health', 'clinical']):
        return "healthcare and medical diagnostics"
    elif any(word in description for word in ['education', 'teaching', 'learning']):
        return "education and academic instruction"
    else:
        return "professional information analysis"

def generate_questions_smart(description_en: str, description_ru: str) -> List[Dict]:
    """Генерация 5 уникальных вопросов с уникальными неправильными ответами"""
    print("   📝 Генерация вопросов...")

    concepts = extract_key_concepts(description_en)
    questions = []

    # Вопрос 1: Основной объект (по содержанию)
    print("      Вопрос 1/5 (основной объект)...")
    q1_answer_en = concepts['main_object']
    q1_answer_ru = translate_to_russian(q1_answer_en)
    q1_wrong_en = generate_unique_wrong_answers(q1_answer_en, description_en, 'content')
    q1_wrong_ru = [translate_to_russian(ans) for ans in q1_wrong_en]
    questions.append(create_question(
        "Что является основным объектом, изображённым на картинке?",
        q1_answer_ru,
        q1_wrong_ru,
        "content"
    ))
    print("         ✅ Создан")

    # Вопрос 2: Детали (по содержанию)
    print("      Вопрос 2/5 (ключевые детали)...")
    q2_answer_en = concepts['detail']
    q2_answer_ru = translate_to_russian(q2_answer_en)
    q2_wrong_en = generate_unique_wrong_answers(q2_answer_en, description_en, 'content')
    q2_wrong_ru = [translate_to_russian(ans) for ans in q2_wrong_en]
    questions.append(create_question(
        "Какие ключевые элементы можно увидеть на изображении?",
        q2_answer_ru,
        q2_wrong_ru,
        "content"
    ))
    print("         ✅ Создан")

    # Вопрос 3: Категория
    print("      Вопрос 3/5 (тип визуализации)...")
    q3_answer_en = concepts['category']
    q3_answer_ru = translate_to_russian(q3_answer_en)
    q3_wrong_en = generate_unique_wrong_answers(q3_answer_en, description_en, 'category')
    q3_wrong_ru = [translate_to_russian(ans) for ans in q3_wrong_en]
    questions.append(create_question(
        "Какой тип визуального представления использован?",
        q3_answer_ru,
        q3_wrong_ru,
        "category"
    ))
    print("         ✅ Создан")

    # Вопрос 4: Назначение
    print("      Вопрос 4/5 (цель/назначение)...")
    q4_answer_en = concepts['purpose']
    q4_answer_ru = translate_to_russian(q4_answer_en)
    q4_wrong_en = generate_unique_wrong_answers(q4_answer_en, description_en, 'purpose')
    q4_wrong_ru = [translate_to_russian(ans) for ans in q4_wrong_en]
    questions.append(create_question(
        "Какова цель или назначение того, что изображено?",
        q4_answer_ru,
        q4_wrong_ru,
        "purpose"
    ))
    print("         ✅ Создан")

    # Вопрос 5: Контекст
    print("      Вопрос 5/5 (контекст применения)...")
    q5_answer_en = concepts['context']
    q5_answer_ru = translate_to_russian(q5_answer_en)
    q5_wrong_en = generate_unique_wrong_answers(q5_answer_en, description_en, 'context')
    q5_wrong_ru = [translate_to_russian(ans) for ans in q5_wrong_en]
    questions.append(create_question(
        "В каком контексте или области это может применяться?",
        q5_answer_ru,
        q5_wrong_ru,
        "context"
    ))
    print("         ✅ Создан")

    print(f"   ✅ Создано {len(questions)} уникальных вопросов")
    return questions

def create_question(question_text: str, correct_answer: str, wrong_answers: List[str], qtype: str) -> Dict:
    """Создает структуру вопроса с перемешанными ответами"""
    all_answers = [correct_answer] + wrong_answers[:3]
    random.shuffle(all_answers)

    correct_index = all_answers.index(correct_answer)

    return {
        "question": question_text,
        "answers": all_answers,
        "correct_answer": correct_index,
        "correct_text": correct_answer,
        "type": qtype
    }

def format_questions_output(questions: List[Dict]) -> str:
    """Форматирование вопросов для отображения"""
    output = "📝 **СГЕНЕРИРОВАННЫЕ ТЕСТОВЫЕ ВОПРОСЫ**\n\n"

    content_questions = sum(1 for q in questions if q.get('type') == 'content')
    output += f"📊 Вопросов по содержанию изображения: **{content_questions}**\n"
    output += f"📚 Всего вопросов: **{len(questions)}**\n\n"
    output += "="*50 + "\n\n"

    for i, q in enumerate(questions, 1):
        marker = "🎯" if q.get('type') == 'content' else "📌"
        output += f"{marker} **Вопрос {i}:** {q['question']}\n\n"

        for j, answer in enumerate(q['answers'], 1):
            check = "✅" if j-1 == q['correct_answer'] else "  "
            # Первая буква строчная, так как это продолжение списка
            output += f"{check} {j}. {answer}\n"

        output += f"\n💡 **Правильный ответ:** {q['correct_text']}\n"
        output += "\n" + "="*50 + "\n\n"

    output += "\n**Условные обозначения:**\n"
    output += "🎯 — вопрос по содержанию изображения\n"
    output += "📌 — общий вопрос\n"

    return output

print("✅ Функции генерации вопросов загружены")

"""## 7️⃣ Основная функция обработки"""

def process_image(image: Image.Image, progress=gr.Progress()) -> Tuple[str, str]:
    """Обработка изображения с генерацией уникальных вопросов"""
    if image is None:
        return "⚠️ Пожалуйста, загрузите изображение", ""

    try:
        print("\n" + "="*60)
        print("🎯 НАЧАЛО ОБРАБОТКИ ИЗОБРАЖЕНИЯ")
        print("="*60)

        start_total = time.time()

        # Анализ изображения
        progress(0.3, desc="Анализ изображения...")
        description_en, description_ru = analyze_image_detailed(image)

        # Генерация вопросов с уникальными неправильными ответами
        progress(0.7, desc="Генерация уникальных вопросов...")
        questions = generate_questions_smart(description_en, description_ru)

        # Форматирование
        progress(0.95, desc="Форматирование результатов...")
        description_output = f"🔍 **ОПИСАНИЕ ИЗОБРАЖЕНИЯ:**\n\n{description_ru}\n\n"
        description_output += f"_Оригинал (EN): {description_en}_"

        questions_output = format_questions_output(questions)

        progress(1.0, desc="Готово!")

        total_time = time.time() - start_total
        print(f"\n✅ ОБРАБОТКА ЗАВЕРШЕНА за {total_time:.2f} сек")
        print("="*60 + "\n")

        return description_output, questions_output

    except Exception as e:
        error_msg = f"❌ Ошибка обработки: {str(e)}"
        print(f"\n{error_msg}\n")
        import traceback
        traceback.print_exc()
        return error_msg, error_msg

print("✅ Функция обработки готова")

"""## 8️⃣ Запуск интерфейса"""

with gr.Blocks(title="AI-ассистент для генерации тестов") as interface:
    gr.Markdown(
        """
        # 🎓 AI-ассистент для генерации тестовых вопросов
        ## ⚡ Финальная версия — полностью уникальные вопросы

        **Возможности:**
        - 🇷🇺 Качественный перевод на русский язык
        - 📝 Детальное описание изображений (BLIP-large)
        - ❓ 5 уникальных тестовых вопросов
        - 🎯 2 вопроса по содержанию изображения
        - 🎲 Случайные неправильные ответы (не повторяются между изображениями)
        - ⚡ Обработка за 10–20 секунд на GPU

        ---
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                type="pil",
                label="📸 Загрузите изображение",
                height=400
            )

            process_btn = gr.Button(
                "🚀 Анализировать и генерировать вопросы",
                variant="primary",
                size="lg"
            )

            gr.Markdown(
                """
                ### 💡 Подсказки:
                - Используйте чёткие изображения
                - Подходят: графики, схемы, диаграммы, фотографии
                - Форматы: JPG, PNG, WEBP

                ### ⚡ Преимущества:
                - ✅ Быстрая обработка (10–20 сек)
                - ✅ Уникальные неправильные ответы
                - ✅ Качественный перевод
                - ✅ 2 вопроса по содержанию
                - ✅ Нет повторений между тестами
                """
            )

        with gr.Column(scale=1):
            description_output = gr.Textbox(
                label="📝 Описание изображения",
                lines=6
            )

            questions_output = gr.Textbox(
                label="📋 Тестовые вопросы (5 уникальных)",
                lines=35
            )

    gr.Markdown(
        """
        ---
        ### 🔧 Технические детали:
        - **Модель анализа:** BLIP-large (детальные описания)
        - **Модель перевода:** NLLB-200 (качественный русский)
        - **Генерация ответов:** динамическая на основе содержания изображения
        - **Устройство:** GPU (T4) — Google Colab
        - **Время обработки:** 10–20 секунд

        ### ✨ Улучшения:
        - Неправильные ответы генерируются динамически для каждого изображения
        - Исключаются варианты с совпадающими ключевыми словами
        - Каждая загрузка даёт новый набор неправильных ответов
        - Исправлено оформление на русском языке (регистр, склонения)
        """
    )

    process_btn.click(
        fn=process_image,
        inputs=[image_input],
        outputs=[description_output, questions_output]
    )

print("\n" + "="*60)
print("🌐 ЗАПУСК ФИНАЛЬНОГО ИНТЕРФЕЙСА")
print("="*60)
print(f"📱 Устройство: {device.upper()}")
print("⏱️  Время обработки: 10–20 секунд")
print("🎲 Уникальные неправильные ответы: ДА")
print("🎯 Вопросов по содержанию: 2")
print("="*60 + "\n")

interface.launch(debug=True, share=True)